language: elixir
matrix:
  include:
    - name: "Elixir 1.3 / OTP 18"
      elixir: 1.3
      otp_release: 18.3
    - name: "Elixir 1.6 / OTP 20"
      elixir: 1.6
      otp_release: 20.0
    - name: "Elixir 1.7 / OTP 20"
      elixir: 1.7
      otp_release: 20.0
    - name: "Elixir 1.7 / OTP 21"
      elixir: 1.7
      otp_release: 21.0
script: MIX_ENV=test mix compile --warnings-as-errors && MIX_ENV=test mix test
